- name: Install frum
  ansible.builtin.unarchive:
    src: "https://github.com/TaKO8Ki/frum/releases/download/v{{ frum_version }}/frum-v{{ frum_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: /usr/bin/
    include: ["frum-v{{ frum_version }}-x86_64-unknown-linux-musl/frum"]
    owner: root
    group: root
    mode: "0755"
    creates: /usr/bin/frum
    remote_src: yes
    extra_opts:
      - --strip-components
      - 1
  become: true

- name: Update profile settings
  copy:
    dest: "~/.bashrc"
    content: |
      eval "$(frum init)"

- name: Check if the Ruby version is already installed
  shell: bash -lc "ruby -v | grep -q {{ ruby_version }}"
  register: ruby_installed
  ignore_errors: true
  check_mode: false

- name: Install Ruby {{ ruby_version }}
  shell: bash -lc "frum install {{ ruby_version }}"
  register: new_ruby_installed
  when: ruby_installed is failed

- name: Set the default Ruby version to {{ ruby_version }}
  shell: bash -lc "frum global {{ ruby_version }}"
  when: new_ruby_installed is succeeded
